- name: checking the variables
  hosts: localhosr
  vars: 
    user: "hari"
    course: "devops"
    time: 3
  tasks:
  - name: printing the variables from locally
    ansible.builtin.debug:
      msg: user name is {{user}} joined {{course}} for {{time}}
  - name: printing the variables from locally
    vars:
      - inventory.ini
    ansible.builtin.debug:
      msg: user name is {{user}} joined {{course}} for {{time}}
      
