- name: checking for the conditions 
  hosts: localhost
  become: yes 
  tasks: 
  - name: check user exist or not 
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: yes
  - name: printing the information output of user 
    ansible.builtin.debug:
      msg: "user info is : {{USER}} "
  - name: say hello 
    ansible.builtin.debug:
      msg: "say hello"