- name: check number 
  hosts: localhost
  become: yes
  tasks:
  - name: user if he won't declare the variable which is printing 
    ansible.builtin.debug:
      msg: "Entered {{string1 | default('Please declare variable')}}"
  
- name: convert dictinary to list 
  hosts: localhost
  vars: 
    My_dict:
      Course: Devops
      Trainer: sivakumar
      Duration: 3 months 
  tasks:
  - name: converting dict to list before
    ansible.builtin.debug:
      msg: "dict valuses before converting lists {{My_dict}}"
  - name: converting dict to list after
    ansible.builtin.debug:
      msg: "dict valuses after converting : {{My_dict | dict2items}}"
  
- name: convert dictinary to list 
  hosts: localhost
  vars: 
    My_list:
      
      - {'key': 'Course', 'value': 'Devops'},
      - {'key': 'Trainer', 'value': 'sivakumar'},
      - {'key': 'Duration', 'value': '3 months'}
      
  tasks:
  - name: converting dict to list before
    ansible.builtin.debug:
      msg: "dict valuses before converting lists {{My_list}}"
  - name: converting dict to list after
    ansible.builtin.debug:
      msg: "dict valuses after converting : {{My_list | items2dict}}"
   