- name: printing the loops
  hosts: localhost
  become: yes
  tasks:
    - name: printing the loops
      ansible.debug,builtin:
        msg: {{item}}
      loop:
      - LINUX
      - MYSQL
      - ANSIBLE