- name: printing the loops
  hosts: localhost
  become: yes
  tasks:
    - name: printing the loops
      ansible.builtin.debug:
        msg: " {{ item }}"
      loop:
      - LINUX
      - MYSQL
      - ANSIBLE