- name: installing the packages
  hosts: localhost
  become: yes
  tasks:
    - name: installing the packages
      ansible.builtin.dnf:
        name: " {{ item }}"
        state: latest
      loop:
      - mysql
      - python
      - ansible