- name: installing the packages
  hosts: localhost
  become: yes
  tasks:
    - name: installing the packages
      ansible.builtin.dnf:
        name: " {{ item.name }}"
        state: "{{item.state}}"
      loop:
      - {name: mysql , state: latest}
      - {name: python , state: absent}
      - {name: postfix , state: latest}