- name: front end configuration
  hosts: localhost
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
  - name: enabling the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  - name: Delete content & directory
    ansible.builtin.file:
      state: absent
      path: /usr/share/nginx/html/*
  